#!/bin/bash
python3 -m py_compile $PYFILE 2>/dev/null
if [ $? -eq 0 ]; then
    mv __pycache__/*.pyc ./$PYFILEc 2>/dev/null
    if [ $? -eq 0 ]; then
        exit 0
    else
        exit 1
    fi
else
    exit 1
fi
